---
title: "入門17 - [ToDoアプリのエラーハンドリングをするPart4]"
---
# ToDoアプリのエラーハンドリングをする
「エラーハンドリング」については、ボリュームが多いので「Part1, Part2, Part3, Part4」という風に分けて解説していきます。それぞれ実施する内容については下記の通りです。

【Part1】
- 存在しないコンテンツ（404エラー）
- ルートモデルバインディングによる重複箇所の除去

【Part2】
- 権限がないコンテンツ（403エラー）
- ポリシーとCanミドルウェアによる重複箇所の除去

【Part3】
- リレーション（関連性）が存在しない（404エラー）

【Part4】
- エラーページを作ろう
- トランザクション処理とtry...catch構文

# ToDoアプリのエラーハンドリングをするPart4
第16章では、オリジナルの「エラーページ」を作成していきます。

# 今回の目標物
今回の目標は、オリジナルの「404ページ, 403ページ, 500ページ」を表示することです。

![](/images/laravel-tutorial-books/17.laravel-todo-app-error-handling-part4/2023-12-05-18-24-51.png =650x)

![](/images/laravel-tutorial-books/17.laravel-todo-app-error-handling-part4/2023-12-05-18-31-52.png =650x)

![](/images/laravel-tutorial-books/17.laravel-todo-app-error-handling-part4/2023-12-05-18-39-08.png =650x)

# ①エラーページを作ろう
第17章では、オリジナルのエラーページを作成する手順を紹介します。

エラーページを作るのは非常に簡単で、`resources/views` ディレクトリにさらに `errors` ディレクトリを作成します。この `errors` ディレクトリに `レスポンスコード.blade.php` という名前でテンプレートを作成すれば、`abort` 関数などでエラー系のレスポンスが作成されるときに対応するファイル名のテンプレートが画面として使われます。

まずは、`errors` ディレクトリ と 各エラーページを作成します。
```js:Terminal
# errorsディレクトリを作成
root~# mkdir resources/views/errors
# 各エラーページを作成
root~# touch resources/views/errors/404.blade.php
root~# touch resources/views/errors/403.blade.php
root~# touch resources/views/errors/500.blade.php
```
それぞれのエラーページを下記のように編集してください。

なお、今回も下記のアカウントで動作確認を実施するものとします。
ブラウザで [http://localhost/folders/login](http://localhost/folders/login) にアクセスしてログインしておいてください。
:::message
【会員テストデータ（Seederテストデータ）】
Email：dummy@email.com
氏名：test
パスワード：test1234
パスワード（確認）：test1234
:::

## 404ページ
404ページは「ページが存在しない」場合のエラーページです。
`404.blade.php` を下記のように編集してください。
```js:404.blade.php
<!--
*   extends()：親ビューを継承する（読み込む）
*   親ビュー名：layout を指定
-->
@extends('layout')

<!--
*   section()：子ビューにsectionでデータを定義する
*   セクション名：content を指定
*   用途：404エラーページを表示する
-->
@section('content')
<div class="container">
    <div class="row">
        <div class="col col-md-offset-3 col-md-6">
            <div class="text-center">
                <h2>404 | NOT FOUND</h2>
                <p>お探しのページは見つかりませんでした。</p>
                <a href="{{ route('home') }}" class="btn">
                    ホームへ戻る
                </a>
            </div>
        </div>
    </div>
</div>
@endsection
```

それでは、確認してみましょう。
ブラウザで [http://localhost/folders/4/tasks/1/edit](http://localhost/folders/4/tasks/1/edit) にアクセスししてください。

![](/images/laravel-tutorial-books/17.laravel-todo-app-error-handling-part4/2023-12-05-10-56-36.png)

オリジナルの `404` ページが表示されればOKです。

今回はタスク編集ページのみを確認していますが他のページでも `404` に該当する場合はオリジナルのエラーページが表示されるようになっています。

## 403ページ
403ページは「ページは存在するが権限がない」などの場合のエラーページです。
下記のように編集してください。
```js:403.blade.php
<!--
*   extends()：親ビューを継承する（読み込む）
*   親ビュー名：layout を指定
-->
@extends('layout')

<!--
*   section()：子ビューにsectionでデータを定義する
*   セクション名：content を指定
*   用途：403エラーページを表示する
-->
@section('content')
<div class="container">
    <div class="row">
        <div class="col col-md-offset-3 col-md-6">
            <div class="text-center">
                <h2>403 | THIS ACTION IS UNAUTHORIZED.</h2>
                <p>お探しのページにアクセスする権限がありません。</p>
                <a href="{{ route('home') }}" class="btn">
                    ホームへ戻る
                </a>
            </div>
        </div>
    </div>
</div>
@endsection
```
それでは、確認してみましょう。
ブラウザで [http://localhost/folders/1/tasks/4/edit](http://localhost/folders/1/tasks/4/edit) にアクセスしてください。

![](/images/laravel-tutorial-books/17.laravel-todo-app-error-handling-part4/2023-12-05-12-36-26.png)

オリジナルの `403` ページが表示されればOKです。

今回はタスク編集ページのみを確認していますが他のページでも `404` に該当する場合はオリジナルのエラーページが表示されるようになっています。

## 500ページ
500ページは「サーバーエラー」などの場合のエラーページです。
DBと通信できない場合やDBの処理に失敗した場合のエラーなどが該当します。
下記のように編集してください。
```js:500.blade.php
<!--
*   extends()：親ビューを継承する（読み込む）
*   親ビュー名：layout を指定
-->
@extends('layout')

<!--
*   section()：子ビューにsectionでデータを定義する
*   セクション名：content を指定
*   用途：500エラーページを表示する
-->
@section('content')
<div class="container">
    <div class="row">
        <div class="col col-md-offset-3 col-md-6">
            <div class="text-center">
                <h2>500 | SERVER ERROR</h2>
                <p>サーバーのエラーが起きました。</p>
                <p>申し訳ありませんが、以下のリンクからホームページへお戻りください。</p>
                <a href="{{ route('home') }}" class="btn">
                    ホームへ戻る
                </a>
            </div>
        </div>
    </div>
</div>
@endsection
```

次に、タスクコントローラーの `index` メソッドが `HTTP:500` エラー になるように修正します。
```js:TaskController.php
public function showEditForm(Folder $folder, Task $task)
{
    // HTTPステータスコード:500を持たせる
    abort(500);
    [中略]
}
```

それでは、確認してみましょう。
次に、ブラウザで [http://localhost/folders/1/tasks/1/edit](http://localhost/folders/1/tasks/1/edit) にアクセスします。

![](/images/laravel-tutorial-books/17.laravel-todo-app-error-handling-part4/2023-12-05-12-40-34.png)

オリジナルの `500` ページが表示されればOKです。

今回はタスク編集ページのみを確認していますが他のページでも `404` に該当する場合はオリジナルのエラーページが表示されるようになっています。

確認が終わったので `abort(500);` は削除しておいてください。

# おまけ - トランザクション処理とtry...catch構文
エラーハンドリング繋がりで「トランザクション処理と`try...catch`構文」をご紹介します。

まずは、トランザクション処理と`try...catch`構文とは何かを確認してみましょう。

下記の記事では「`transaction`メソッド」を使う方法が紹介されています。
シンプルで分かりやすいので一読しておきましょう。
https://www.happylifecreators.com/blog/20220513/

また、下記の記事では「`beginTransaction`メソッド」を使う方法も紹介されています。
今ではアンチパターンとされてますが知識としては知っておくと良いと思います。
今でも良く見かける実装方法だからです。
https://shinyasunamachi.com/blog/Laravelでトランザクション処理のエラーハンドリングを行う方法

概要と実装方法は把握されたでしょうか。

「トランザクション」とは、お互いに関連ある複数の処理を、まとめて行いひとつの処理とすることをあらわす言葉です。例えば、フォルダの削除機能は、フォルダを削除するとフォルダの中にあるタスクも削除します。この時にフォルダの削除は成功してタスクの削除は失敗したとします。ここ場合はタスクだけが残るのでおかしいということになります。

「`try...catch`構文」とは、`try`内で記述されたコードにエラーが発生したら`catch`で捕まえる構文です。捕まえたエラーをどうするかを`catch`内のコードで命令していくことになります。

それではToDoアプリでも「トランザクション処理と`try...catch`構文」を実装してみましょう。

まずは、ToDOアプリでトランザクション処理が必要な箇所を考えてみます。
複数のデータベース処理がされているのはどこでしょうか？ 
フォルダーコントローラーの `delete`メソッド だけですね。
つまり、トランザクション処理が必要なのはこの部分だけということになります。

次に、`try...catch`構文について考えてみます。
今回は、`laravel.log` にエラーを記録することにしたいと考えてます。
そうなるとコントローラーのメソッドすべてを対象範囲にしたいところです。

適用範囲がわかったのでそれぞれを下記のように編集してください。

:::details FolderController.php の記述内容
```js:
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;
use App\Models\Folder;
use App\Http\Requests\CreateFolder;
use App\Http\Requests\EditFolder;

class FolderController extends Controller
{
    /**
     *  【フォルダ作成ページの表示機能】
     *
     *  GET /folders/create
     *  @return \Illuminate\View\View
     */
    public function showCreateForm()
    {
        try {
            /** @var App\Models\User **/
            $user = Auth::user();
            $user->folders;

            return view('folders/create');

        } catch (\Throwable $e) {
            Log::error('Error FolderController in showCreateForm: ' . $e->getMessage());
        }
    }

    /**
     *  【フォルダの作成機能】
     *
     *  POST /folders/create
     *  @param CreateFolder $request （Requestクラスの機能は引き継がれる）
     *  @return \Illuminate\Http\RedirectResponse
     *  @var App\Http\Requests\CreateFolder
     */
    public function create(CreateFolder $request)
    {
        try {
            $folder = new Folder();
            $folder->title = $request->title;

            /** @var App\Models\User **/
            $user = Auth::user();
            $user->folders()->save($folder);

            return redirect()->route('tasks.index', [
                'folder' => $folder->id,
            ]);
        } catch (\Exception $e) {
            Log::error('Error FolderController in create: ' . $e->getMessage());
        }
    }

    /**
     *  【フォルダ編集ページの表示機能】
     *
     *  GET /folders/{folder}/edit
     *  @param Folder $folder
     *  @return \Illuminate\View\View
     */
    public function showEditForm(Folder $folder)
    {
        try {
            /** @var App\Models\User **/
            $user = Auth::user();
            $folder = $user->folders()->findOrFail($folder->id);

            return view('folders/edit', [
                'folder_id' => $folder->id,
                'folder_title' => $folder->title,
            ]);
        } catch (\Throwable $e) {
            Log::error('Error FolderController in showEditForm: ' . $e->getMessage());
        }
    }

    /**
     *  【フォルダの編集機能】
     *
     *  POST /folders/{folder}/edit
     *  @param Folder $folder
     *  @param EditTask $request
     *  @return \Illuminate\Http\RedirectResponse
     */
    public function edit(Folder $folder, EditFolder $request)
    {
        try {
            /** @var App\Models\User **/
            $user = Auth::user();
            $folder = $user->folders()->findOrFail($folder->id);
            $folder->title = $request->title;
            $folder->save();

            return redirect()->route('tasks.index', [
                'folder' => $folder->id,
            ]);
        } catch (\Throwable $e) {
            Log::error('Error FolderController in edit: ' . $e->getMessage());
        }
    }

    /**
     *  【フォルダ削除ページの表示機能】
     *
     *  GET /folders/{folder}/delete
     *  @param Folder $folder
     *  @return \Illuminate\View\View
     */
    public function showDeleteForm(Folder $folder)
    {
        try {
            /** @var App\Models\User **/
            $user = Auth::user();
            $folder = $user->folders()->findOrFail($folder->id);

            return view('folders/delete', [
                'folder_id' => $folder->id,
                'folder_title' => $folder->title,
            ]);
        } catch (\Throwable $e) {
            Log::error('Error in showDeleteForm: ' . $e->getMessage());
        }
    }

    /**
     *  【フォルダの削除機能】
     *
     *  POST /folders/{folder}/delete
     *  @param Folder $folder
     *  @return RedirectResponse
     */
    public function delete(Folder $folder)
    {
        try {
            /** @var App\Models\User **/
            $user = Auth::user();
            $folder = $user->folders()->findOrFail($folder->id);

            $folder = DB::transaction(function () use ($folder) {
                if($folder) throw new \Exception('500');
                $folder->tasks()->delete();
                $folder->delete();
                return $folder;
            });

            $folder = Folder::first();

            return redirect()->route('tasks.index', [
                'folder' => $folder->id
            ]);
        } catch (\Throwable $e) {
            Log::error('Error FolderController in delete: ' . $e->getMessage());
        }
    }
}
```
:::
:::details TaskController.php の記述内容
```js:
<?php
namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;
use App\Models\Folder;
use App\Models\Task;
use App\Http\Requests\CreateTask;
use App\Http\Requests\EditTask;

class TaskController extends Controller
{
    /**
     *  【タスク一覧ページの表示機能】
     *
     *  GET /folders/{folder}/tasks
     *  @param Folder $folder
     *  @return \Illuminate\View\View
     */
    public function index(Folder $folder)
    {
        try {
            /** @var App\Models\User **/
            $user = auth()->user();
            $folders = $user->folders()->get();
            $tasks = $folder->tasks()->get();

            return view('tasks/index', [
                'folders' => $folders,
                'folder_id' => $folder->id,
                'tasks' => $tasks
            ]);
        } catch (\Throwable $e) {
            Log::error('Error TaskController in index: ' . $e->getMessage());
        }
    }

    /**
     *  【タスク作成ページの表示機能】
     *
     *  GET /folders/{folder}/tasks/create
     *  @param Folder $folder
     *  @return \Illuminate\View\View
     */
    public function showCreateForm(Folder $folder)
    {
        try {
            /** @var App\Models\User **/
            $user = Auth::user();
            $folder = $user->folders()->findOrFail($folder->id);

            return view('tasks/create', [
                'folder_id' => $folder->id,
            ]);
        } catch (\Throwable $e) {
            Log::error('Error TaskController in showCreateForm: ' . $e->getMessage());
        }
    }

    /**
     *  【タスクの作成機能】
     *
     *  POST /folders/{folder}/tasks/create
     *  @param Folder $folder
     *  @param CreateTask $request
     *  @return \Illuminate\Http\RedirectResponse
     *  @var App\Http\Requests\CreateTask
     */
    public function create(Folder $folder, CreateTask $request)
    {
        try {
            /** @var App\Models\User **/
            $user = Auth::user();
            $folder = $user->folders()->findOrFail($folder->id);

            $task = new Task();
            $task->title = $request->title;
            $task->due_date = $request->due_date;
            $folder->tasks()->save($task);

            return redirect()->route('tasks.index', [
                'folder' => $folder->id,
            ]);
        } catch (\Throwable $e) {
            Log::error('Error TaskController in create: ' . $e->getMessage());
        }
    }

    /**
     *  【タスク編集ページの表示機能】
     *
     *  GET /folders/{folder}/tasks/{task}/edit
     *  @param Folder $folder
     *  @param Task $task
     *  @return \Illuminate\View\View
     */
    public function showEditForm(Folder $folder, Task $task)
    {
        try {
            $this->checkRelation($folder, $task);

            /** @var App\Models\User **/
            $user = Auth::user();
            $folder = $user->folders()->findOrFail($folder->id);
            $task = $folder->tasks()->findOrFail($task->id);

            return view('tasks/edit', [
                'task' => $task,
            ]);
        } catch (\Throwable $e) {
            Log::error('Error TaskController in showEditForm: ' . $e->getMessage());
        }
    }

    /**
     *  【タスクの編集機能】
     *
     *  POST /folders/{folder}/tasks/{task}/edit
     *  @param Folder $folder
     *  @param Task $task
     *  @param EditTask $request
     *  @return \Illuminate\Http\RedirectResponse
     */
    public function edit(Folder $folder, Task $task, EditTask $request)
    {
        try {
            $this->checkRelation($folder, $task);

            /** @var App\Models\User **/
            $user = Auth::user();
            $folder = $user->folders()->findOrFail($folder->id);
            $task = $folder->tasks()->findOrFail($task->id);

            $task->title = $request->title;
            $task->status = $request->status;
            $task->due_date = $request->due_date;
            $task->save();

            return redirect()->route('tasks.index', [
                'folder' => $task->folder_id,
            ]);
        } catch (\Throwable $e) {
            Log::error('Error TaskController in edit: ' . $e->getMessage());
        }
    }

    /**
     *  【タスク削除ページの表示機能】
     *
     *  GET /folders/{folder}/tasks/{task}/delete
     *  @param Folder $folder
     *  @param Task $task
     *  @return \Illuminate\View\View
     */
    public function showDeleteForm(Folder $folder, Task $task)
    {
        try {
            $this->checkRelation($folder, $task);

            /** @var App\Models\User **/
            $user = Auth::user();
            $folder = $user->folders()->findOrFail($folder->id);
            $task = $folder->tasks()->findOrFail($task->id);

            return view('tasks/delete', [
                'task' => $task,
            ]);
        } catch (\Throwable $e) {
            Log::error('Error TaskController in showDeleteForm: ' . $e->getMessage());
        }
    }

    /**
     *  【タスクの削除機能】
     *
     *  POST /folders/{folder}/tasks/{task}/delete
     *  @param Folder $folder
     *  @param Task $task
     *  @return \Illuminate\View\View
     */
    public function delete(Folder $folder, Task $task)
    {
        try {
            $this->checkRelation($folder, $task);

            /** @var App\Models\User **/
            $user = Auth::user();
            $folder = $user->folders()->findOrFail($folder->id);
            $task = $folder->tasks()->findOrFail($task->id);

            $task->delete();

            return redirect()->route('tasks.index', [
                'folder' => $task->folder_id
            ]);
        } catch (\Throwable $e) {
            Log::error('Error TaskController in delete: ' . $e->getMessage());
        }
    }

    /**
     *  【フォルダーとタスクの関連性チェック機能】
     *
     *  @param Folder $folder
     *  @param Task $task
     *  @return void
     */
    private function checkRelation(Folder $folder, Task $task)
    {
        if ($folder->id !== $task->folder_id) {
            abort(404);
        }
    }
}
```
:::
:::details HomeController.php の記述内容
```js:
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * ホームページを表示する
     *
     * GET /
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        try {
            /** @var App\Models\User **/
            $user = Auth::user();

            $folder = $user->folders()->first();

            if (is_null($folder)) {
                return view('home');
            }

            return redirect()->route('tasks.index', [
                'folder' => $folder->id,
            ]);
        } catch (\Throwable $e) {
            Log::error('Error HomeController in index: ' . $e->getMessage());
        }
    }
}
```
:::

それではここから意図的にエラーを発生するようにしてみます。

まずは、`laravel.log` をクリアしておきましょう。

```js:Terminal
root@~# php artisan log:clear
# または
root@~# rm storage/logs/laravel.log
```
これにより、`laravel.log` ファイルが削除されます。
そしてログイベント発生時に新しい `laravel.log` が再作成されます。

次に、意図的にエラーを発生されるコードを記述します。
今回はフォルダコントローラーの `delete` メソッドでエラーを発生させることにします。
下記のようにエラーを発生させるコードを埋め込みましょう。

```js:FolderController.php
public function delete(Folder $folder)
{
    [中略]
    $folder = DB::transaction(function () use ($folder) {
        if($folder) throw new \Exception('500');
        [中略]
    });
    [中略]
}
```

上記では `throw new \Exception();` で例外をスローしています。
`if($folder)` の変数名は埋め込むメソッドによって書き換えることになります。

それでは、ブラウザからフォルダーの削除を実行してみてください。
```js:laravel.log
[2023-12-07 13:37:54] local.ERROR: Error FolderController in delete: 500   
```
上記のようにエラーが `laravel.log` に記録されたはずです。
他のメソッドについても同様にエラーを埋め込んで検証することは同じです。

これで「`try...catch`構文とトランザクション処理」のエラーハンドリングは完了しました。

# まとめ
この章では、ToDoアプリのエラーハンドリングしました。

ここまでの内容で下記のように

- オリジナルの404ページを表示する実装
- オリジナルの403ページを表示する実装
- オリジナルの500ページを表示する実装
- おまけ - トランザクション処理とtry...catch構文を実装

などを実施しました。

前回に引き続き基本の `CRUD` ではなく応用技術を実施しました。

そしてここまでで ToDoアプリケーション の実装は完了しました。
機能は多くないですが、しっかり動作する一人前のアプリを作成できたと思います。
Laravelの基礎としては十分に網羅的に学べたことになります。
少なくとも基本的な用語を交えて会話が成立するくらいにはなれているいるはずです。

実務では今回よりも要件も複雑で高度なことが要求されてくるでしょう。
ここで学んだことだけでは与えられたタスクを完遂できることは出来ないはずです。

それに経験豊富な人でも新規プロジェクトは分からないことだらけだったりします。
私たちエンジニアはいつだって準備不足で分からないことに直面します。

そんな時に「何も分からない」と「分からないことがある」は大きな違いだと感じています。
何より基本的な用語を交えて会話が成立するなら協力を得てタスクを完遂できます。
これは本当に大きな違いです。皆様はすでに基本的な用語で会話が成立するはずです。

「Laravel入門 - Laravelを使ってみよう!」が皆様の一助になれれば幸いです。

ここまでのソースコードを下記に掲載しておきます。
確認などにご活用ください。
https://github.com/eguchi244/Laravel9-Tutorial-PJ/tree/Chapter17/ToDoアプリのエラーハンドリングをするPart4
